# DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vibehub_dev?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

jwt.secret=K8fT2mQ9zX4vB7nH1yR5cD0LwE6UjA3pSgVxCqM8oN2tYlZ7rP4kFhJ1aW9dB6