# DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vibehub_stg?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

jwt.secret=R3vN8cX1kM5tZ7pQ2Wb4yH9L0aE6DgFjSxUoCqTnK8mYlVhP1rA5dJwB3zG2f