# DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vibehub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

jwt.secret=Z1pT9XqM4rH7kC2Lw8Vb5D0gY3aN6sJfUeRjWcA2nP9oKxFh7tB4mQ1yE8dG5